SKILLS = {
    "python": ["python"],
    "java": ["java"],
    "sql": ["sql", "mysql", "postgresql", "sqlite"],
    "machine learning": ["machine learning", "ml"],
    "deep learning": ["deep learning", "dl"],
    "data analysis": ["data analysis", "data analytics", "eda"],
    "statistics": ["statistics", "probability"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "tensorflow": ["tensorflow"],
    "keras": ["keras"],
    "pytorch": ["pytorch", "torch"],
    "nlp": ["nlp", "natural language processing"],
    "transformers": ["transformers", "hugging face", "bert", "gpt"],
    "computer vision": ["computer vision", "opencv"],
    "data science": ["data science", "datascience"],
    "feature engineering": ["feature engineering"],
    "model deployment": ["model deployment", "mlops", "model serving"],
    "docker": ["docker"],
    "kubernetes": ["kubernetes", "k8s"],
    "aws": ["aws", "s3", "ec2", "lambda", "sageMaker", "sagemaker"],
    "gcp": ["gcp", "google cloud", "vertex ai"],
    "azure": ["azure"],
    "fastapi": ["fastapi"],
    "flask": ["flask"],
    "git": ["git", "github"],
}